retry

diff --git a/.github/actions/build-node-python/action.yml b/.github/actions/build-node-python/action.yml
--- a/.github/actions/build-node-python/action.yml
+++ b/.github/actions/build-node-python/action.yml
@@ -124,26 +124,26 @@ runs:
           touch ~/.gitconfig
         fi
 
-        git config --global pack.packSizeLimit 1g
-        git config --global pack.deltaCacheSize 1g
-        git config --global pack.windowMemory 1g
-        git config --global core.packedGitLimit 1g
-        git config --global core.packedGitWindowSize 1g
+        #git config --global pack.packSizeLimit 1g
+        #git config --global pack.deltaCacheSize 1g
+        #git config --global pack.windowMemory 1g
+        #git config --global core.packedGitLimit 1g
+        #git config --global core.packedGitWindowSize 1g
 
-        git config --global http.postBuffer 10g
-        git config --global http.maxRequestBuffer 10g
-        git config --global https.postBuffer 10g
-        git config --global https.maxRequestBuffer 10g
-        
+        #git config --global http.postBuffer 10g
+        #git config --global http.maxRequestBuffer 10g
+        #git config --global https.postBuffer 10g
+        #git config --global https.maxRequestBuffer 10g
+
         git config --global http.timeout 600
         git config --global core.compression 9
 
         git config --global pack.window 1
         git config --global pack.depth 1
-        git config --global pack.threads 128
+        #git config --global pack.threads 128
 
-        git config --global http.lowSpeedLimit 100
-        git config --global http.lowSpeedTime 300
+        #git config --global http.lowSpeedLimit 100
+        #git config --global http.lowSpeedTime 300
 
         git config --global --replace-all url."https://$GITHUB_TOKEN@github.com/".insteadOf ssh://git@github.com/
         git config --add --global url."https://$GITHUB_TOKEN@github".insteadOf https://github
@@ -180,7 +180,11 @@ runs:
           set -e
           
           for i in {1..3}; do
-            yarn install --no-immutable --inline-builds && break || sleep 15
+            echo "Attempt $i of 3: Installing dependencies..."
+            yarn install --no-immutable --inline-builds && break || {
+              echo "Attempt $i failed. Retrying in 15 seconds..."
+              sleep 15
+            }
           done
 
           parallel_jobs=()
