add build python

diff --git a/.github/workflows/build-product.yml b/.github/workflows/build-product.yml
--- a/.github/workflows/build-product.yml
+++ b/.github/workflows/build-product.yml
@@ -132,27 +132,126 @@ jobs:
           echo "::set-output name=aws::$aws"
           echo "::set-output name=image_tag1::$image_tag1"
           echo "::set-output name=image_tag2::$image_tag2"
-  build-node:
+  # build-node:
+  #   needs: prepare-build 
+  #   runs-on: ubuntu-20.04
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       node-version: ["14.19"]
+  #   steps: 
+  #     # checkout specific repository    
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}
+  #     - name: Set up node version ${{ matrix.node-version }}
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
+  #         registry-url: ${{ env.NPM_REGISTRY }}
+  #     - name: Show node and npm version
+  #       run: |
+  #         node -v
+  #         npm -v
+  #     - name: Git config
+  #       if: "${{ env.GITHUB_TOKEN != '' }}"
+  #       run: |
+  #         git config --global url.https://${{ env.GITHUB_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
+  #       env: 
+  #         GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}       
+  #     - name: Install generator
+  #       run: |
+  #         npm install -g yo@4.3.0
+  #         npm install -g generator-phovea@${{ env.GENERATOR_VERSION }}
+  #     - name: create workspace
+  #       run: |
+  #         mkdir -p ./tmp/web
+  #         cd ./tmp/web
+  #         name=$(jq  -rc '.[] | select(.type == "web") | .repo' ../../phovea_product.json)
+  #         name=$(echo "$name" | sed -e 's|.*/||')
+  #         repository=https://${{ env.GITHUB_TOKEN }}@github.com/$(jq  -rc '.[] | select(.type == "web") | .repo' ../../phovea_product.json).git
+  #         branch=$(jq  -rc '.[] | select(.type == "web") | .branch' ../../phovea_product.json)
+  #         git clone -b $branch --depth 1 $repository $name
+  #         readarray -t my_array < <(jq  -rc '.[] | select(.type == "web") | .additional[]' ../../phovea_product.json)
+  #         for additional in "${my_array[@]}"; do
+  #           echo "$additional"
+  #           name=$(echo $additional | jq  -rc '.name')
+  #           name=$(echo "$name" | sed -e 's|.*/||')
+  #           echo "$name"
+  #           repository=https://${{ env.GITHUB_TOKEN }}@github.com/$(echo $additional | jq  -rc '.repo').git
+  #           branch=$(echo $additional | jq  -rc '.branch')
+  #           echo "$repository"
+  #           echo "$branch"
+  #           git clone -b $branch --depth 1 $repository $name
+  #         done
+  #       env: 
+  #         GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}           
+  #     - name: update workspace
+  #       run: |
+  #         cd ./tmp/web
+  #         rm ./../../.yo-rc.json
+  #         yo phovea:workspace --defaultApp=${{ needs.prepare-build.outputs.app }} --noAdditionals=true  --addWorkspaceRepos=false
+  #         yes | cp -r ./../../templates/web/* .
+  #     - name: install dependencies
+  #       run: |
+  #         cd ./tmp/web
+  #         npm i     
+  #     - name: show installed dependencies
+  #       run: |
+  #         cd ./tmp/web
+  #         npm list --depth=1 || true
+  #     - name: Build
+  #       run: |
+  #         cd ./tmp/web
+  #         npm run dist
+  #     - name: Configure AWS Credentials
+  #       if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
+  #         aws-region: eu-central-1
+  #     - name: Login to Amazon ECR
+  #       if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}      
+  #       id: login-ecr
+  #       uses: aws-actions/amazon-ecr-login@v1
+  #     - name: Build, tag, and push image to Amazon ECR
+  #       if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}      
+  #       env:
+  #         ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
+  #         ECR_REPOSITORY: ${{ needs.prepare-build.outputs.web_repo }}
+  #         IMAGE_TAG1: ${{ needs.prepare-build.outputs.image_tag1 }}
+  #         IMAGE_TAG2: ${{ needs.prepare-build.outputs.image_tag2 }}
+  #       run: |
+  #         cd ./tmp/web
+  #         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2 -f ./deploy/web/Dockerfile .
+  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1
+  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
+  #     - name: Log out from Amazon ECR
+  #       if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' && always() }}      
+  #       run: docker logout ${{ steps.login-ecr.outputs.registry }}
+  build-python:
     needs: prepare-build 
     runs-on: ubuntu-20.04
     strategy:
       fail-fast: false
       matrix:
-        node-version: ["14.19"]
+        python-version: ["3.10"]
     steps: 
       # checkout specific repository    
       - uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}
-      - name: Set up node version ${{ matrix.node-version }}
+      # need node because of the generator
+      - name: Set up node version 
         uses: actions/setup-node@v3
         with:
-          node-version: ${{ matrix.node-version }}
-          registry-url: ${{ env.NPM_REGISTRY }}
-      - name: Show node and npm version
+          node-version: "14.19"
+      - name: Set up python ${{ matrix.python-version }}
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Show python and pip version
         run: |
-          node -v
-          npm -v
+          python --version
+          pip --version
       - name: Git config
         if: "${{ env.GITHUB_TOKEN != '' }}"
         run: |
@@ -165,8 +264,8 @@ jobs:
           npm install -g generator-phovea@${{ env.GENERATOR_VERSION }}
       - name: create workspace
         run: |
-          mkdir -p ./tmp/web
-          cd ./tmp/web
+          mkdir -p ./tmp/api
+          cd ./tmp/api
           name=$(jq  -rc '.[] | select(.type == "api") | .repo' ../../phovea_product.json)
           name=$(echo "$name" | sed -e 's|.*/||')
           repository=https://${{ env.GITHUB_TOKEN }}@github.com/$(jq  -rc '.[] | select(.type == "api") | .repo' ../../phovea_product.json).git
@@ -188,22 +287,35 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}           
       - name: update workspace
         run: |
-          cd ./tmp/web
+          cd ./tmp/api
           rm ./../../.yo-rc.json
           yo phovea:workspace --defaultApp=${{ needs.prepare-build.outputs.app }} --noAdditionals=true  --addWorkspaceRepos=false
-          yes | cp -r ./../../templates/web/* .
+          yes | cp -r ./../../templates/api/* .
       - name: install dependencies
         run: |
-          cd ./tmp/web
+          cd ./tmp/api
           npm i     
       - name: show installed dependencies
         run: |
-          cd ./tmp/web
+          cd ./tmp/api
           npm list --depth=1 || true
       - name: Build
         run: |
-          cd ./tmp/web
-          npm run dist
+          cd ./tmp/api
+          name=$(jq  -rc '.[] | select(.type == "api") | .repo' ../../phovea_product.json)
+          name=$(echo "$name" | sed -e 's|.*/||')
+          cd $name
+          make build
+          cd ..
+          readarray -t my_array < <(jq  -rc '.[] | select(.type == "api") | .additional[]' ../../phovea_product.json)
+          for additional in "${my_array[@]}"; do
+            echo "$additional"
+            name=$(echo $additional | jq  -rc '.name')
+            name=$(echo "$name" | sed -e 's|.*/||')
+            echo "$name"
+            cd $name
+            make build
+          done
       - name: Configure AWS Credentials
         if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}
         uses: aws-actions/configure-aws-credentials@v1
@@ -218,19 +330,19 @@ jobs:
         if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}      
         env:
           ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
-          ECR_REPOSITORY: ${{ needs.prepare-build.outputs.web_repo }}
+          ECR_REPOSITORY: ${{ needs.prepare-build.outputs.api_repo }}
           IMAGE_TAG1: ${{ needs.prepare-build.outputs.image_tag1 }}
           IMAGE_TAG2: ${{ needs.prepare-build.outputs.image_tag2 }}
         run: |
-          cd ./tmp/web
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2 -f ./deploy/web/Dockerfile .
+          cd ./tmp/api
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2 -f ./deploy/api/Dockerfile .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
       - name: Log out from Amazon ECR
         if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' && always() }}      
-        run: docker logout ${{ steps.login-ecr.outputs.registry }}
+        run: docker logout ${{ steps.login-ecr.outputs.registry }}        
   deploy:
-    needs: [prepare-build, build-node] 
+    needs: [prepare-build, build-python] 
     runs-on: ubuntu-20.04
     if: ${{ needs.prepare-build.outputs.stage == 'develop' }}
     steps:           
