fix version number checks

diff --git a/.github/workflows/release-source.yml b/.github/workflows/release-source.yml
--- a/.github/workflows/release-source.yml
+++ b/.github/workflows/release-source.yml
@@ -81,50 +81,34 @@ jobs:
           file_minor=$(echo "$file_release_version" | cut -d'.' -f2)
           file_patch=$(echo "$file_release_version" | cut -d'.' -f3)
 
-
           input_major=$(echo "$input_release_version" | cut -d'.' -f1)
           input_minor=$(echo "$input_release_version" | cut -d'.' -f2)
           input_patch=$(echo "$input_release_version" | cut -d'.' -f3)
 
-          max_major=$(("$file_major" + 1))  
-          max_minor=$(("$file_minor" + 1))
-          max_patch=$(("$file_patch" + 1))
-
-          echo "max versions: $max_major.$max_minor.$max_patch"
-
-
-          if [ "$input_major" -gt "$max_major" ]; then
-            echo "Error: Major version cannot be greater than the current version by more than 1."
-            exit 1
-          elif [ "$input_minor" -gt "$max_minor" ]; then
-            echo "Error: Minor version cannot be greater than the current version by more than 1."
-            exit 1
-          elif [ "$input_patch" -gt "$max_patch" ]; then
-            echo "Error: Patch version cannot be greater than the current version by more than 1."
-            exit 1
-          elif [ "$input_major" -lt "$file_major" ]; then
-            echo "Error: Major version cannot be less than the current version."
-            exit 1
-          elif [ "$input_minor" -lt "$file_minor" ]; then
-            if [ "$input_major" -eq "$max_major" ] && [ "$input_minor" -eq 0 ] && [ "$input_patch" -eq 0 ]; then
-              echo "Valid version input"
+          if [ "$input_major" -eq "$file_major" ]; then
+            if [ "$input_minor" -eq "$file_minor" ]; then
+              if [ "$input_patch" -gt "$file_patch" ]; then
+                echo "Valid patch version input"
+              else
+                echo "Error: Patch version cannot be less than or equal to the current version."
+                exit 1
+              fi
+            elif [ "$input_minor" -gt "$file_minor" ] && [ "$input_patch" -eq 0 ]; then
+              echo "Valid minor version input"
             else
-              echo "Error: Minor version cannot be less than the current version."
+              echo "Error: Minor version is invalid."
               exit 1
             fi
-          elif [ "$input_patch" -lt "$file_patch" ]; then
-            if [ "$input_major" -eq "$max_major" ] && [ "$input_minor" -eq 0 ] && [ "$input_patch" -eq 0 ]; then
-              echo "Valid version input"
-            elif [ "$input_major" -eq "$file_major" ] && [ "$input_minor" -eq "$max_minor" ] && [ "$input_patch" -eq 0 ]; then
-              echo "Valid version input"
-            else
-              echo "Error: Patch version cannot be less than the current version."
-              exit 1
-            fi
+          elif [ "$input_major" -gt "$file_major" ] && [ "$input_minor" -eq 0 ] && [ "$input_patch" -eq 0 ]; then
+            echo "Valid major version input"
+          else
+            echo "Error: Version input is invalid based on semantic versioning rules."
+            exit 1
           fi
+
           echo "New version is $input_major.$input_minor.$input_patch"
           echo "RELEASE_VERSION=$input_release_version" >> "$GITHUB_ENV"
-          
+  
       - name: create release branch
         run: |
           git config user.name "$GITHUB_ACTOR"
