Add release version input to release-source workflow
Fix lint in release-source.yml

Fix lint in release-source.yml

Fix lint in release-source.yml

Fix version validation error in release-source.yml

Fix lint

Fix lint in release-source.yml

Remove empty line in release-source workflow

Update release_version input to be required in release-source.yml

Update release-source workflow

Update release-source workflow inputs

Update release-source workflow to use workflow_dispatch event

Update release-source workflow

Fix file_release_version extraction in release-source.yml

Add version increment logic

Fix version comparison bug

Fix version validation in release-source.yml

extend  version comparison logic in release-source.yml

Fix version comparison bug in release-source.yml

Fix version comparison bug in release-source.yml

Fix version comparison bug in release-source.yml

Fix version comparison bug in release-source.yml

Fix version comparison bug in release-source.yml

Fix version comparison bug in release-source.yml

Fix version comparison bug in release-source.yml

Fix version comparison bug in release-source.yml

diff --git a/.github/workflows/release-source.yml b/.github/workflows/release-source.yml
--- a/.github/workflows/release-source.yml
+++ b/.github/workflows/release-source.yml
@@ -2,6 +2,7 @@ name: release-source
 
 on:
   workflow_call:
+    
 
 permissions:
   contents: write
@@ -43,11 +44,76 @@ jobs:
           dv_devops: ${{ vars.DV_DEVOPS }}
           actor: ${{ github.actor }}
           qms_are_allowed: "false"
-      - name: get release version
+      - name: get release version from package.json
         id: get-release-version
+        if: ${{ github.event.inputs.release_version == null }}
         run: |
           release_version="$(jq -r '.version' package.json | cut -d '-' -f 1)"
           echo "RELEASE_VERSION=$release_version" >> "$GITHUB_ENV"
+      - name: get release version from input
+        id: get-release-version-from-input
+        if: ${{ github.event.inputs.release_version != null }}
+        run: |
+          input_release_version="${{ github.event.inputs.release_version }}"
+          if echo "$input_release_version" | grep -q '^[0-9.]*$'; then
+            echo "valind input"
+          else
+            echo "Error: invaled input version."
+            exit 1
+          fi
+
+          file_release_version="$(jq -r '.version' package.json | cut -d '-' -f 1)"
+          file_release_version="$(echo $file_release_version | sed 's/[^0-9.]*//g')"
+          echo "file_release_version=$file_release_version"
+          file_major=$(echo "$file_release_version" | cut -d'.' -f1)
+          file_minor=$(echo "$file_release_version" | cut -d'.' -f2)
+          file_patch=$(echo "$file_release_version" | cut -d'.' -f3)
+
+
+          input_major=$(echo "$input_release_version" | cut -d'.' -f1)
+          input_minor=$(echo "$input_release_version" | cut -d'.' -f2)
+          input_patch=$(echo "$input_release_version" | cut -d'.' -f3)
+
+          max_major=$(("$file_major" + 1))  
+          max_minor=$(("$file_minor" + 1))
+          max_patch=$(("$file_patch" + 1))
+
+          echo "max versions: $max_major.$max_minor.$max_patch"
+
+
+          if [ "$input_major" -gt "$max_major" ]; then
+            echo "Error: Major version cannot be greater than the current version by more than 1."
+            exit 1
+          elif [ "$input_minor" -gt "$max_minor" ]; then
+            echo "Error: Minor version cannot be greater than the current version by more than 1."
+            exit 1
+          elif [ "$input_patch" -gt "$max_patch" ]; then
+            echo "Error: Patch version cannot be greater than the current version by more than 1."
+            exit 1
+          elif [ "$input_major" -lt "$file_major" ]; then
+            echo "Error: Major version cannot be less than the current version."
+            exit 1
+          elif [ "$input_minor" -lt "$file_minor" ]; then
+            if [ "$input_major" -eq "$max_major" ] && [ "$input_minor" -eq 0 ] && [ "$input_patch" -eq 0 ]; then
+              echo "New version is $input_major.$input_minor.$input_patch"
+            else
+              echo "Error: Minor version cannot be less than the current version."
+              exit 1
+            fi
+          elif [ "$input_patch" -lt "$file_patch" ]; then
+            if [ "$input_major" -eq "$max_major" ] && [ "$input_minor" -eq 0 ] && [ "$input_patch" -eq 0 ]; then
+              echo "New version is $input_major.$input_minor.$input_patch"
+            elif [ "$input_major" -eq "$file_major" ] && [ "$input_minor" -eq "$max_minor" ] && [ "$input_patch" -eq 0 ]; then
+              echo "New version is $input_major.$input_minor.$input_patch"
+            else
+              echo "Error: Patch version cannot be less than the current version."
+              exit 1
+            fi
+          fi
+          
+          release_version=$input_release_version
+          echo "RELEASE_VERSION=$release_version" >> "$GITHUB_ENV"
+          
       - name: create release branch
         run: |
           git config user.name "$GITHUB_ACTOR"
