feat: add support for releasing repos without package.json

diff --git a/.github/workflows/release-source.yml b/.github/workflows/release-source.yml
--- a/.github/workflows/release-source.yml
+++ b/.github/workflows/release-source.yml
@@ -81,6 +81,15 @@ jobs:
           actor: ${{ github.actor }}
           qms_are_allowed: "false"
 
+      - name: check for package.json
+        id: check-package-json
+        run: |
+          if [ -f "package.json" ]; then
+            echo "is_package_json=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "is_package_json=false" >> "$GITHUB_OUTPUT"
+          fi
+
       - name: get release version from input
         if: ${{ inputs.skip_branch_check == false }}
         id: get-release-version-from-input
@@ -93,38 +102,41 @@ jobs:
             exit 1
           fi
 
-          file_release_version="$(jq -r '.version' package.json | cut -d '-' -f 1)"
-          file_release_version="${file_release_version//[^0-9.]}"
-          echo "file_release_version=$file_release_version"
-          file_major=$(echo "$file_release_version" | cut -d'.' -f1)
-          file_minor=$(echo "$file_release_version" | cut -d'.' -f2)
-          file_patch=$(echo "$file_release_version" | cut -d'.' -f3)
+          # Check if package.json exists and validate the version against it
+          if [ "${{ steps.check-package-json.outputs.is_package_json }}" == "true" ]; then
+            file_release_version="$(jq -r '.version' package.json | cut -d '-' -f 1)"
+            file_release_version="${file_release_version//[^0-9.]}"
+            echo "file_release_version=$file_release_version"
+            file_major=$(echo "$file_release_version" | cut -d'.' -f1)
+            file_minor=$(echo "$file_release_version" | cut -d'.' -f2)
+            file_patch=$(echo "$file_release_version" | cut -d'.' -f3)
 
-          echo "Stable release version: $file_major.$file_minor.$file_patch"
+            echo "Stable release version: $file_major.$file_minor.$file_patch"
 
-          input_major=$(echo "$input_release_version" | cut -d'.' -f1)
-          input_minor=$(echo "$input_release_version" | cut -d'.' -f2)
-          input_patch=$(echo "$input_release_version" | cut -d'.' -f3)
+            input_major=$(echo "$input_release_version" | cut -d'.' -f1)
+            input_minor=$(echo "$input_release_version" | cut -d'.' -f2)
+            input_patch=$(echo "$input_release_version" | cut -d'.' -f3)
 
-          if [ "$input_major" -eq "$file_major" ]; then
-            if [ "$input_minor" -eq "$file_minor" ]; then
-              if [ "$input_patch" -eq "$file_patch" ]; then
-                echo "Valid patch version input"
+            if [ "$input_major" -eq "$file_major" ]; then
+              if [ "$input_minor" -eq "$file_minor" ]; then
+                if [ "$input_patch" -eq "$file_patch" ]; then
+                  echo "Valid patch version input"
+                else
+                  echo "Error: Patch version must match the package.json version without the -SNAPSHOT suffix."
+                  exit 1
+                fi
+              elif [ "$input_minor" -gt "$file_minor" ] && [ "$input_patch" -eq 0 ]; then
+                echo "Valid minor version input"
               else
-                echo "Error: Patch version must match the package.json version without the -SNAPSHOT suffix."
+                echo "Error: Minor version is invalid."
                 exit 1
               fi
-            elif [ "$input_minor" -gt "$file_minor" ] && [ "$input_patch" -eq 0 ]; then
-              echo "Valid minor version input"
+            elif [ "$input_major" -gt "$file_major" ] && [ "$input_minor" -eq 0 ] && [ "$input_patch" -eq 0 ]; then
+              echo "Valid major version input"
             else
-              echo "Error: Minor version is invalid."
+              echo "Error: Version input is invalid based on semantic versioning rules."
               exit 1
             fi
-          elif [ "$input_major" -gt "$file_major" ] && [ "$input_minor" -eq 0 ] && [ "$input_patch" -eq 0 ]; then
-            echo "Valid major version input"
-          else
-            echo "Error: Version input is invalid based on semantic versioning rules."
-            exit 1
           fi
 
           echo "New version is $input_major.$input_minor.$input_patch"
@@ -136,6 +148,7 @@ jobs:
           git config user.email "<>"
           git checkout -b release-"$RELEASE_VERSION"
       - name: Update package.json
+        if: ${{ steps.check-package-json.outputs.is_package_json == 'true' }}
         run: |
           sed -i "s/^\(\s*\)\"version\".*/\1\"version\": \"$RELEASE_VERSION\",/" package.json
           git add package.json
@@ -225,7 +238,7 @@ jobs:
           git add .
       - name: Commit changes
         run: |
-          git commit -m "Prepare release version $RELEASE_VERSION"
+          git commit --allow-empty -m "Prepare release version $RELEASE_VERSION"
       - name: push all changes
         run: |
           git push origin release-"$RELEASE_VERSION"
